"""initial schema

Revision ID: a2546b8ec0d1
Revises: 
Create Date: 2026-08-18 14:51:25.090669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a2546b8ec0d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_name', ['name'], unique=False)

    op.create_table('webhook_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('endpoint_url', sa.String(length=2048), nullable=False),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_configs', schema=None) as batch_op:
        batch_op.create_index('idx_webhook_config_active', ['is_active'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='task_priority'), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='task_status'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_deadline', ['deadline'], unique=False)
        batch_op.create_index('idx_tasks_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_tasks_status', ['status'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.Enum('DAY_H', 'RELATIVE', 'ABSOLUTE', name='reminder_type'), nullable=False),
    sa.Column('relative_value', sa.Integer(), nullable=True),
    sa.Column('relative_unit', sa.Enum('MINUTES', 'HOURS', 'DAYS', name='reminder_unit'), nullable=True),
    sa.Column('absolute_time', sa.DateTime(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index('idx_reminders_task_id', ['task_id'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('reminder_id', sa.Integer(), nullable=True),
    sa.Column('webhook_config_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status'), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['webhook_config_id'], ['webhook_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index('idx_notification_log_created', ['created_at'], unique=False)
        batch_op.create_index('idx_notification_log_reminder_id', ['reminder_id'], unique=False)
        batch_op.create_index('idx_notification_log_status', ['status'], unique=False)
        batch_op.create_index('idx_notification_log_task_id', ['task_id'], unique=False)
        batch_op.create_index('idx_notification_log_webhook_id', ['webhook_config_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_log_webhook_id')
        batch_op.drop_index('idx_notification_log_task_id')
        batch_op.drop_index('idx_notification_log_status')
        batch_op.drop_index('idx_notification_log_reminder_id')
        batch_op.drop_index('idx_notification_log_created')

    op.drop_table('notification_logs')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index('idx_reminders_task_id')

    op.drop_table('reminders')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_status')
        batch_op.drop_index('idx_tasks_project_id')
        batch_op.drop_index('idx_tasks_deadline')

    op.drop_table('tasks')
    with op.batch_alter_table('webhook_configs', schema=None) as batch_op:
        batch_op.drop_index('idx_webhook_config_active')

    op.drop_table('webhook_configs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_name')

    op.drop_table('projects')
    # ### end Alembic commands ###
